import { block, indent, joinLines } from "@/lib/deployment/templates/format";

export type ApacheTemplateInput = {
  serverName: string;
  upstreamHost: string;
  upstreamPort: number;
  accessLog?: string;
  errorLog?: string;
  tlsCertPath?: string;
  tlsKeyPath?: string;
};

export function generateApacheConfig(input: ApacheTemplateInput): string {
  const vhost = joinLines([
    "<VirtualHost *:80>",
    indent(
      2,
      joinLines([
        `ServerName ${input.serverName}`,
        input.accessLog ? `CustomLog ${input.accessLog} combined` : "",
        input.errorLog ? `ErrorLog ${input.errorLog}` : "",
        "ProxyPreserveHost On",
        "RequestHeader set X-Forwarded-Proto \"expr=%{REQUEST_SCHEME}\"",
        `ProxyPass / http://${input.upstreamHost}:${input.upstreamPort}/`,
        `ProxyPassReverse / http://${input.upstreamHost}:${input.upstreamPort}/`,
        "",
        "# WebSocket upgrade (requires proxy_wstunnel)",
        "RewriteEngine on",
        "RewriteCond %{HTTP:Upgrade} websocket [NC]",
        "RewriteCond %{HTTP:Connection} upgrade [NC]",
        `RewriteRule ^/?(.*) ws://${input.upstreamHost}:${input.upstreamPort}/$1 [P,L]`
      ])
    ),
    "</VirtualHost>"
  ]);

  const ssl =
    input.tlsCertPath && input.tlsKeyPath
      ? joinLines([
          "",
          "<VirtualHost *:443>",
          indent(
            2,
            joinLines([
              `ServerName ${input.serverName}`,
              `SSLEngine on`,
              `SSLCertificateFile ${input.tlsCertPath}`,
              `SSLCertificateKeyFile ${input.tlsKeyPath}`,
              `ProxyPass / http://${input.upstreamHost}:${input.upstreamPort}/`,
              `ProxyPassReverse / http://${input.upstreamHost}:${input.upstreamPort}/`
            ])
          ),
          "</VirtualHost>"
        ])
      : "\n# Add :443 VirtualHost when TLS cert paths are configured";

  return joinLines([
    "# Generated by central-server",
    "# Requires: a2enmod proxy proxy_http proxy_wstunnel ssl rewrite headers",
    vhost,
    ssl
  ]);
}
