import { indent, joinLines } from "@/lib/deployment/templates/format";
import {
  httpRedirectServer,
  resolveNginxTlsPaths,
  type NginxTemplateInput
} from "@/lib/deployment/templates/nginx-common";
import { appRootFromDeploymentPath, currentSymlinkPath } from "@/lib/deploy/releases";

export type StaticNginxInput = NginxTemplateInput & {
  documentRoot: string;
};

function staticLocationBlock(): string {
  return joinLines([
    "location / {",
    indent(4, "try_files $uri $uri/ /index.html;"),
    "}"
  ]);
}

function staticHttpsServer(input: StaticNginxInput): string {
  return joinLines([
    "server {",
    indent(
      4,
      joinLines([
        "listen 443 ssl http2;",
        "listen [::]:443 ssl http2;",
        `server_name ${input.serverName};`,
        "",
        `root ${input.documentRoot};`,
        "index index.html;",
        "",
        `ssl_certificate ${input.tlsCertPath};`,
        `ssl_certificate_key ${input.tlsKeyPath};`,
        "",
        staticLocationBlock()
      ])
    ),
    "}"
  ]);
}

function staticHttpServer(input: StaticNginxInput): string {
  return joinLines([
    "server {",
    indent(
      4,
      joinLines([
        "listen 80;",
        "listen [::]:80;",
        `server_name ${input.serverName};`,
        "",
        `root ${input.documentRoot};`,
        "index index.html;",
        "",
        staticLocationBlock()
      ])
    ),
    "}"
  ]);
}

/** Document root for static sites under release layout (`current`). */
export function staticDocumentRoot(deploymentPath: string): string {
  const appRoot = appRootFromDeploymentPath(deploymentPath);
  const current = currentSymlinkPath(appRoot);
  if (current.endsWith("/current")) return current;
  return `${appRoot}/current`;
}

export function generateStaticNginxConfig(input: NginxTemplateInput): string {
  const deployPath = input.deploymentPath?.trim() || "/var/www/app";
  const documentRoot = staticDocumentRoot(deployPath);
  const tls = resolveNginxTlsPaths(input);
  const withTls: StaticNginxInput = {
    ...input,
    documentRoot,
    tlsCertPath: tls?.cert,
    tlsKeyPath: tls?.key
  };
  const hasTls = Boolean(tls?.cert && tls?.key);

  const blocks = hasTls
    ? [httpRedirectServer(withTls.serverName), "", staticHttpsServer(withTls)]
    : [staticHttpServer(withTls)];

  return joinLines([
    "# Generated by central-server (static)",
    "",
    ...blocks
  ]);
}
