import { indent, joinLines } from "@/lib/deployment/templates/format";
import {
  httpRedirectServer,
  inferPhpFpmSocket,
  isPhpFpmStack,
  laravelDocumentRoot,
  normalizeFramework,
  resolveNginxTlsPaths,
  type NginxTemplateInput
} from "@/lib/deployment/templates/nginx-common";
import { generateLaravelNginxConfig } from "@/lib/deployment/templates/nginx-laravel";
import { generateStaticNginxConfig } from "@/lib/deployment/templates/nginx-static";
import { isStaticStack } from "@/lib/deployment/templates/nginx-common";

export type { NginxTemplateInput } from "@/lib/deployment/templates/nginx-common";
export {
  primaryServerHostname,
  resolveNginxTlsPaths,
  laravelDocumentRoot,
  inferPhpFpmSocket,
  isPhpFpmStack
} from "@/lib/deployment/templates/nginx-common";

function proxyLocationBlock(upstreamUrl: string): string {
  return joinLines([
    "location / {",
    indent(
      4,
      joinLines([
        `proxy_pass ${upstreamUrl};`,
        "proxy_http_version 1.1;",
        "",
        "proxy_set_header Host $host;",
        "proxy_set_header X-Real-IP $remote_addr;",
        "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
        "proxy_set_header X-Forwarded-Proto $scheme;",
        "",
        "proxy_set_header Upgrade $http_upgrade;",
        'proxy_set_header Connection "upgrade";',
        "",
        "proxy_read_timeout 60s;",
        "proxy_send_timeout 60s;",
        "",
        "proxy_cache_bypass $http_upgrade;"
      ])
    ),
    "}"
  ]);
}

function proxyHttpsServer(input: NginxTemplateInput, upstreamUrl: string): string {
  const bodySize = input.clientMaxBodySize ?? "50M";
  const logs =
    input.accessLog || input.errorLog
      ? joinLines([
          input.accessLog ? `access_log ${input.accessLog};` : "",
          input.errorLog ? `error_log ${input.errorLog};` : "",
          ""
        ])
      : "";

  return joinLines([
    "server {",
    indent(
      4,
      joinLines([
        "listen 443 ssl;",
        "listen [::]:443 ssl;",
        "http2 on;",
        `server_name ${input.serverName};`,
        "",
        `ssl_certificate ${input.tlsCertPath};`,
        `ssl_certificate_key ${input.tlsKeyPath};`,
        "",
        `client_max_body_size ${bodySize};`,
        "",
        logs,
        proxyLocationBlock(upstreamUrl)
      ])
    ),
    "}"
  ]);
}

function proxyHttpOnlyServer(input: NginxTemplateInput, upstreamUrl: string): string {
  const bodySize = input.clientMaxBodySize ?? "50M";
  const logs =
    input.accessLog || input.errorLog
      ? joinLines([
          input.accessLog ? `access_log ${input.accessLog};` : "",
          input.errorLog ? `error_log ${input.errorLog};` : "",
          ""
        ])
      : "";

  return joinLines([
    "server {",
    indent(
      4,
      joinLines([
        "listen 80;",
        "listen [::]:80;",
        `server_name ${input.serverName};`,
        "",
        `client_max_body_size ${bodySize};`,
        "",
        logs,
        proxyLocationBlock(upstreamUrl)
      ])
    ),
    "}"
  ]);
}

function generateProxyNginxConfig(input: NginxTemplateInput): string {
  const upstreamUrl = `http://${input.upstreamHost}:${input.upstreamPort}`;
  const tls = resolveNginxTlsPaths({
    tlsCertPath: input.tlsCertPath,
    tlsKeyPath: input.tlsKeyPath,
    serverName: input.serverName
  });
  const withTls: NginxTemplateInput = {
    ...input,
    tlsCertPath: tls?.cert,
    tlsKeyPath: tls?.key
  };
  const hasTls = Boolean(tls?.cert && tls?.key);

  const blocks = hasTls
    ? [httpRedirectServer(withTls.serverName), "", proxyHttpsServer(withTls, upstreamUrl)]
    : [proxyHttpOnlyServer(withTls, upstreamUrl)];

  return joinLines([
    `# Generated by central-server (${normalizeFramework(input.framework) || "proxy"})`,
    "",
    ...blocks
  ]);
}

/**
 * Nginx site config chosen from detected stack:
 * - laravel / php / php-fpm → PHP-FPM + public root
 * - node, nextjs, etc. → reverse proxy to app port
 */
export function generateNginxConfig(input: NginxTemplateInput & { runtime?: string | null }): string {
  const fw = normalizeFramework(input.framework);

  if (isStaticStack(input.framework, input.runtime)) {
    return generateStaticNginxConfig(input);
  }

  if (isPhpFpmStack(input.framework, input.runtime) || fw === "laravel") {
    const deployPath = input.deploymentPath?.trim() || "/var/www/app";
    return generateLaravelNginxConfig({
      ...input,
      documentRoot: laravelDocumentRoot(deployPath),
      phpFpmSocket: inferPhpFpmSocket(input.restartCommand)
    });
  }

  return generateProxyNginxConfig(input);
}
