import { indent, joinLines } from "@/lib/deployment/templates/format";
import {
  dashboardEmbedNginxLines,
  httpRedirectServer,
  resolveNginxTlsPaths,
  type NginxTemplateInput
} from "@/lib/deployment/templates/nginx-common";

export type LaravelNginxInput = NginxTemplateInput & {
  documentRoot: string;
  phpFpmSocket: string;
};

function laravelHttpsServer(input: LaravelNginxInput): string {
  return joinLines([
    "server {",
    indent(
      4,
      joinLines([
        "listen 443 ssl;",
        "listen [::]:443 ssl;",
        "http2 on;",
        `server_name ${input.serverName};`,
        "",
        `root ${input.documentRoot};`,
        "index index.php index.html index.htm;",
        "",
        `ssl_certificate ${input.tlsCertPath};`,
        `ssl_certificate_key ${input.tlsKeyPath};`,
        "ssl_protocols TLSv1.2 TLSv1.3;",
        "",
        ...dashboardEmbedNginxLines(),
        'add_header X-Content-Type-Options "nosniff" always;',
        "",
        "charset utf-8;",
        "",
        "location / {",
        indent(4, "try_files $uri $uri/ /index.php?$query_string;"),
        "}",
        "",
        "location = /favicon.ico { access_log off; log_not_found off; }",
        "location = /robots.txt  { access_log off; log_not_found off; }",
        "",
        "error_page 404 /index.php;",
        "",
        "location ~ \\.php$ {",
        indent(
          4,
          joinLines([
            "include snippets/fastcgi-php.conf;",
            `fastcgi_pass ${input.phpFpmSocket};`,
            "fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;",
            "include fastcgi_params;"
          ])
        ),
        "}",
        "",
        "location ~ /\\.(?!well-known).* {",
        indent(4, "deny all;"),
        "}"
      ])
    ),
    "}"
  ]);
}

function laravelHttpOnlyServer(input: LaravelNginxInput): string {
  return joinLines([
    "server {",
    indent(
      4,
      joinLines([
        "listen 80;",
        "listen [::]:80;",
        `server_name ${input.serverName};`,
        "",
        `root ${input.documentRoot};`,
        "index index.php index.html index.htm;",
        "",
        "charset utf-8;",
        "",
        "location / {",
        indent(4, "try_files $uri $uri/ /index.php?$query_string;"),
        "}",
        "",
        "location = /favicon.ico { access_log off; log_not_found off; }",
        "location = /robots.txt  { access_log off; log_not_found off; }",
        "",
        "error_page 404 /index.php;",
        "",
        "location ~ \\.php$ {",
        indent(
          4,
          joinLines([
            "include snippets/fastcgi-php.conf;",
            `fastcgi_pass ${input.phpFpmSocket};`,
            "fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;",
            "include fastcgi_params;"
          ])
        ),
        "}",
        "",
        "location ~ /\\.(?!well-known).* {",
        indent(4, "deny all;"),
        "}"
      ])
    ),
    "}"
  ]);
}

export function generateLaravelNginxConfig(input: LaravelNginxInput): string {
  const tls = resolveNginxTlsPaths({
    tlsCertPath: input.tlsCertPath,
    tlsKeyPath: input.tlsKeyPath,
    serverName: input.serverName
  });
  const withTls: LaravelNginxInput = {
    ...input,
    tlsCertPath: tls?.cert,
    tlsKeyPath: tls?.key
  };
  const hasTls = Boolean(tls?.cert && tls?.key);

  const blocks = hasTls
    ? [httpRedirectServer(withTls.serverName), "", laravelHttpsServer(withTls)]
    : [laravelHttpOnlyServer(withTls)];

  return joinLines(["# Generated by central-server (laravel)", "", ...blocks]);
}
