export type Pm2EnvRecord = Record<string, string>;

export type Pm2TemplateInput = {
  appName: string;
  cwd: string;
  script: string;
  args?: string;
  interpreter?: "none";
  instances?: number;
  env: Pm2EnvRecord;
  outFile: string;
  errorFile: string;
};

export function generatePM2Config(input: Pm2TemplateInput): string {
  const apps = [
    {
      name: input.appName,
      cwd: input.cwd,
      script: input.script,
      ...(input.args ? { args: input.args } : {}),
      ...(input.interpreter ? { interpreter: input.interpreter } : {}),
      instances: input.instances ?? 1,
      exec_mode: (input.instances ?? 1) > 1 ? "cluster" : "fork",
      autorestart: true,
      max_restarts: 10,
      exp_backoff_restart_delay: 2000,
      env: input.env,
      error_file: input.errorFile,
      out_file: input.outFile,
      merge_logs: true,
      time: true
    }
  ];
  return `/** Generated by central-server */\nmodule.exports = { apps: ${JSON.stringify(apps, null, 2)} };\n`;
}
